"""removed duplicates

Revision ID: a0a5c8fc5ae5
Revises: 33f8575ff29b
Create Date: 2026-06-06 16:08:22.882303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a5c8fc5ae5'
down_revision = '33f8575ff29b'
branch_labels = None
depends_on = None


def upgrade():
    pass


    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_material', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('section_id')

    # ### end Alembic commands ###
