"""added message

Revision ID: e60e145319de
Revises: f557b70d6cac
Create Date: 2026-01-05 11:04:04.112605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60e145319de'
down_revision = 'f557b70d6cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('file_name')
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
