"""modified database

Revision ID: f557b70d6cac
Revises: 6e567a51ac14
Create Date: 2025-12-24 11:33:14.692932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f557b70d6cac'
down_revision = '6e567a51ac14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('weekly_study_hours', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('preferred_session_length', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('learning_pace', sa.String(length=20), nullable=True))

    with op.batch_alter_table('tutor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teaching_style', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('years_experience', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('specializations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('teaching_philosophy', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('min_session_length', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('max_students', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('preferred_age_groups', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('location')
        batch_op.drop_column('phone')

    with op.batch_alter_table('tutor_profile', schema=None) as batch_op:
        batch_op.drop_column('preferred_age_groups')
        batch_op.drop_column('max_students')
        batch_op.drop_column('min_session_length')
        batch_op.drop_column('teaching_philosophy')
        batch_op.drop_column('specializations')
        batch_op.drop_column('certifications')
        batch_op.drop_column('education')
        batch_op.drop_column('years_experience')
        batch_op.drop_column('teaching_style')

    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_column('learning_pace')
        batch_op.drop_column('preferred_session_length')
        batch_op.drop_column('weekly_study_hours')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
